name: Refresh Version

on:
  workflow_dispatch:  # Allow manual triggering only

jobs:
  refresh-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run version check and update README
        run: |
          node version_check.js
          node generate_readme.js

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: Update contract versions and README'
          title: 'Update contract versions and README'
          body: |
            This PR updates the contract versions JSON file and the README.md with the latest contract versions.
          branch: update-contract-versions
          delete-branch: true
